#%RAML 1.0
title: reksio
uses:
  resType: !include data/common/resourceTypes.raml
  dataType: !include data/types.raml
version: v1
baseUri: http://reks.io

securitySchemes:
- basic:
    description: |
      basic authorization https://tools.ietf.org/html/rfc2617
    type: Basic Authentication

securedBy: [basic]

/Users:
  type:  { resType.PageableCollection: {item : dataType.User} }
  post:
    securedBy: []
    body:
      application/json:
        type: dataType.NewUser
  /{username}:
    type:  { resType.Member: {item : dataType.User} }
/Links:
  type:  { resType.Collection: {item : dataType.Link} }
  /{LinkId}:
    type:  { resType.Member: {item : dataType.Link} }


/Groups:
  type: { resType.PageableCollection: {item : dataType.Group} }
  post:
  /{GroupId}:
    type:  { resType.Member: {item : dataType.Group} }
    /Subscriptions:
      type:  { resType.PageableCollection: {item : dataType.Subscription} }
      /{username}:
        put:
          description: add user to a group
        delete:
          description: remove user from a group
    /Links:
      type:  { resType.PageableCollection: {item : dataType.Link} }
      /{LinkId}:
        put:
          description: add link to a group
        delete:
          description: remove link from a group
