#%RAML 1.0
title: reksio
uses:
  resType: !include data/common/resourceTypes.raml
  dataType: !include data/types.raml
version: v1
baseUri: http://reks.io

securitySchemes:
- basic:
    description: |
      basic authorization https://tools.ietf.org/html/rfc2617
    type: Basic Authentication

securedBy: [basic]

/Users:
  type:  { resType.PageableCollection: {item : dataType.User} }
  post:
    securedBy: []
    body:
      application/json:
        type: dataType.NewUser
  /{username}:
    type:  { resType.Member: {item : dataType.User} }
    /Votes:
      type: { resType.PageableCollection: {item : dataType.UserVote} }
      post:
        body:
          application/json:
            type: dataType.UserVote
      /{LinkId}:
        type: { resType.Member: {item : dataType.Vote} }

/Links:
  type:  { resType.PageableCollection: {item : dataType.Link} }
  post:
    securedBy: []
    body:
      application/json:
        type: dataType.NewLink
  /{LinkId}:
    type:  { resType.Member: {item : dataType.Link} }
    /Stats:
      description: stats for link
    /Votes:
      type: { resType.PageableCollection: {item : dataType.LinkVote} }
      post:
        body:
          application/json:
            type: dataType.LinkVote
      /{username}:
        type: { resType.Member: {item : dataType.Vote} }

/Groups:
  type: { resType.PageableCollection: {item : dataType.Group} }
  post:
  /{GroupId}:
    type:  { resType.Member: {item : dataType.Group} }
    /Subscriptions:
      type:  { resType.PageableCollection: {item : dataType.Subscription} }
      /{username}:
        type: resType.Base
        put:
          description: add user to a group
          responses:
            204:
        delete:
          description: remove user from a group
          responses:
            204:
    /Links:
      type:  { resType.PageableCollection: {item : dataType.Link} }
      /{LinkId}:
        type: resType.Base
        put:
          description: add link to a group
          responses:
            204:
        delete:
          description: remove link from a group
          responses:
            204:
