#%RAML 1.0
title: reksio
version: v1
baseUri: http://reks.io

securitySchemes:
- basic:
    description: |
      basic authorization https://tools.ietf.org/html/rfc2617
    type: Basic Authentication

securedBy: basic

/Users:
  post:
    securedBy: []
    description: |
      Add new user
    body:
      application/json:
        schema: |
          {
            "email": "string",
            "password": "string"
          }
        example: |
          {
            "email": "example@example.com",
            "password": "alamakota"
          }
    responses:
      201:
        description: |
          Succesfully created a new resource
        headers:
          Location:
            description: |
              Location of the newly created resource
            type: string
            required: false
  get:
    description: |
      Retrieve resource
    responses:
      200:
        description: |
          Succesfully retrieved resource
        body:
          application/json:
            schema: |
              {
                "subscribedGroupsIDs": [ "string" ]
              }
            example: |
              {
                "subscribedGroupsIDs": [
                  "satan1",
                  "satan2",
                  "satan3"
                ]
              }

/Links:
  get:
    description: |
      Retrieve resource
    responses:
      200:
        description: |
          Succesfully retrieved resource
  post:
    description: |
      Create a new resource
    body:
      application/json: !!null
    responses:
      201:
        description: |
          Succesfully created a new resource
        headers:
          Location:
            description: |
              Location of the newly created resource
            type: string
            required: false
  /{LinkId}:
    delete:
      description: |
        Delete resource
      responses:
        204:
          description: |
            Succesfully deleted resource
    put:
      description: |
        Update an existing resource
      body:
        application/json:
      responses:
        204:
          description: |
            Succesfully updated the resource

/Groups:
  get:
    description: |
      Retrieve count and array of IDs
    queryParameters:
      limitFrom: number
      limitTo: number
    responses:
      200:
        description: |
          Succesfully retrieved resource
        body:
          application/json:
            schema: |
              {
                "groupsIDs": [ "string" ],
                "totalCount": "number"
              }
            example: |
              {
                "groupsIDs": [ "stan1", "satan2", "satan3" ],
                "totalCount": 50
              }
  post:
    description: |
      Create a new resource
    body:
      application/json: !!null
    responses:
      201:
        description: |
          Succesfully created a new resource
        headers:
          Location:
            description: |
              Location of the newly created resource
            type: string
            required: false
  /{GroupId}:
    get:
      description: |
        Retrieve group
      responses:
        200:
          description: |
            Succesfully retrieved resource
          body:
            application/json:
              example: !include "examples/groups/group.example.json"
              schema: !include "examples/groups/group.schema.json"
    /Subscriptions:
      post:
        description: |
          Subscribe to a group
        body:
          application/json: !!null
        responses:
          201:
            description: |
              Succesfully created a new resource
            headers:
              Location:
                description: |
                  Location of the newly created resource
                type: string
                required: false
      get:
        description: |
          Retrieve resource
        responses:
          200:
            description: |
              Succesfully retrieved resource
